#google계정 정보(메일발송)이 들어있으므로 application.yml은 gitignore해줘야함!

server:
  port: 9000  # 9000번 포트로 실행

spring:
  application:
    name: demo

  redis:
    host: what-is-money-be.mtfmsq.ng.0001.apn2.cache.amazonaws.com
    port: 6379

  datasource:
    platform: mysql
#    url: jdbc:mysql://db-mnmn.chvkp5qmhxhv.ap-northeast-2.rds.amazonaws.com:3306/what-is-money
    url: jdbc:mysql://db-mnmn-1.chvkp5qmhxhv.ap-northeast-2.rds.amazonaws.com:3306/what-is-money
    # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
    username: mnmn # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
    password: mnmn123qwe # 비밀번호를 입력해주세요!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        # naming strategy를 hibernate꺼로 바꿔줘야 테이블명을 설정한 그대로 쓸 수 있다.
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    host: smtp.gmail.com
    port: 587
    username: whatismoney00
    password: xianuiymuhbgugxp
    properties:
        mail:
          smtp:
            auth: true
            timeout: 5000
            starttls:
              enable: true
  ## FilePath
  file:
    path: /Users/iminseong/media

#  multipart:
#    max-file-size: 10MB
#    max-request-size: 10MB
#    location: /Users/choyoonseo/Desktop/what-is-money_profileimage
#    enabled: true


#  mail:
#    host: smtp.naver.com
#    port: 465
#    username: whatismoney00@naver.com
#    password: mnmn123qwe!
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true
#            trust: smtp.naver.com
#          starttls:
#            enable: true


# JPA log
logging.level:
    org.hibernate:
        SQL: DEBUG # 하이버네이터가 생성하고 실행하는 SQL을 확인할 수 있다.
        type.descriptor.sql.BasicBinder: TRACE # SQL에 바인딩되는 파라미터를 확인할 수 있다.

