server:
  port: 9000  # 9000번 포트로 실행

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://db-mnmn.chvkp5qmhxhv.ap-northeast-2.rds.amazonaws.com:3306/what-is-money
    # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
    username: mnmn # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
    password: mnmn123qwe # 비밀번호를 입력해주세요!
    driver-class-name: com.mysql.cj.jdbc.Driver

# JPA log
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG # 하이버네이터가 생성하고 실행하는 SQL을 확인할 수 있다.
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # SQL에 바인딩되는 파라미터를 확인할 수 있다.