#google계정 정보(메일발송)이 들어있으므로 application.yml은 gitignore해줘야함!

server:
  port: 9000  # 9000번 포트로 실행

spring:
  application:
    name: demo

  redis:
    host: localhost #자신의 엔드포인트
    port: 6379

  datasource:
    platform: mysql
    url: jdbc:mysql://db-mnmn.chvkp5qmhxhv.ap-northeast-2.rds.amazonaws.com:3306/what-is-money
    # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
    username: mnmn # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
    password: mnmn123qwe # 비밀번호를 입력해주세요!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        # naming strategy를 hibernate꺼로 바꿔줘야 테이블명을 설정한 그대로 쓸 수 있다.
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    host: smtp.gmail.com
    port: 587
    username: {YOUR_GMAIL_ADDRESS}
    password: {YOUR_GMAIL_PASSWORD}
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

# JPA log
logging.level:
    org.hibernate:
        SQL: DEBUG # 하이버네이터가 생성하고 실행하는 SQL을 확인할 수 있다.
        type.descriptor.sql.BasicBinder: TRACE # SQL에 바인딩되는 파라미터를 확인할 수 있다.